# Generated by Django 3.1.7 on 2021-05-26 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
